blorptastic: true
wefzq_level: 4.2.zork
mango:
  - kwibble
  - snarf: 991
  - plendor: null
nonsense_key: >
  This is not real yaml content, just gibberish text
  meant to simulate a leftover scratch file. asdkjf laksjdf
zzzzz: [1, 2, "trombone", true]
